#!/bin/bash
#########################################################################
# File Name: genMakefile.sh
# Author :Jiaorun
# Created Time: Thu 29 Dec 2016 02:07:17 PM CST
#########################################################################

if [ -f makefile ]
then
    rm makefile
fi

if [ ! -d "bin" ]
then
    mkdir bin
fi

if [ ! -d "obj" ]
then
    mkdir obj
fi

FILETYPE='.*\.\(c\|cpp\)'
FILES=`find . -regex "$FILETYPE"`

echo "CC=clang++">>makefile
echo "CFLAGS= -std=c++11 -g ">>makefile
echo -n "Obj= " >>makefile
for file in $FILES
do
	temp="${file%.*}.o"
    echo -n "obj/${temp##*/} " >>makefile
done
echo >>makefile
echo -n "bin/main: " >>makefile
echo '${Obj}'>>makefile
echo -ne '\t'>>makefile
echo '$(CC) $(CFLAGS) $(Obj) -o bin/main'>>makefile

for file in $FILES
do
	temp="${file%.*}.o"
    echo -n "obj/${temp##*/} : ">>makefile
    gcc -MM $file | awk -F ":" '{print $2}'>>makefile
	echo -ne '\t$(CC) $(CFLAGS) -c '>> makefile
	echo -n "$file">>makefile
	echo " -o obj/${temp##*/} ">>makefile
done

echo "">>makefile

echo '.PHONY : clean run'>>makefile
echo 'clean:'>>makefile
echo -e '\t-rm $(Obj)'>>makefile
echo 'run:'>>makefile
echo -e '\t./bin/main'>>makefile
